## Table of Contents
  > ### DIFFICULTY: 
  > - [x] Easy
  > - [ ] Medium
  > - [ ] Hard
  
<li><a href='#Say "Hello, World!" With Python'>Say "Hello, World!" With Python</a></li>
<li><a href="#Python If-Else">Python If-Else</a></li>
<li><a href="#Arithmetic Operators">Arithmetic Operators</a></li>
<li><a href="#Python: Division">Python: Division</a></li>
<li><a href="#Loops">Loops</a></li>
<li><a href="#Print Function">Print Function</a></li>
<li><a href="#collections.Counter()">collections.Counter()</a></li>
<li><a href="#List Comprehensions">List Comprehensions</a></li>
<li><a href="#Find the Runner-Up Score!">Find the Runner-Up Score!</a></li>
<li><a href="#Nested Lists">Nested Lists</a></li>
<li><a href="#Finding the percentage">Finding the percentage</a></li>
<li><a href="#Lists">Lists</a></li>
<li><a href="#Tuples">Tuples</a></li>
<li><a href="#sWAP cASE">sWAP cASE</a></li>
<li><a href="#String Split and Join">String Split and Join</a></li>
<li><a href="#What's Your Name?">What's Your Name?</a></li>
<li><a href="#Find a string">Find a string</a></li>
<li><a href="#String Validators">String Validators</a></li>
<li><a href="#Text Alignment">Text Alignment</a></li>
<li><a href="#Text Wrap">Text Wrap</a></li>
<li><a href="#Designer Door Mat">Designer Door Mat</a></li>
<li><a href="#String Formatting">String Formatting</a></li>
<li><a href="#Alphabet Rangoli">Alphabet Rangoli</a></li>
<li><a href="#Capitalize!">Capitalize!</a></li>
<li><a href="#itertools.product()">itertools.product()</a></li>
<li><a href="#itertools.permutations()">itertools.permutations()</a></li>
<li><a href="#Polar Coordinates">Polar Coordinates</a></li>
<li><a href="#Introduction to Sets">Introduction to Sets</a></li>
<li><a href="#Calendar Module">Calendar Module</a></li>
<li><a href="#Exceptions">Exceptions</a></li>
<li><a href="#Collections.namedtuple()">Collections.namedtuple()</a></li>
<li><a href="#Collections.OrderedDict()">Collections.OrderedDict()</a></li>
<li><a href="#Symmetric Difference">Symmetric Difference</a></li>
<li><a href="#itertools.combinations()">itertools.combinations()</a></li>
<li><a href="#Incorrect Regex">Incorrect Regex</a></li>
<li><a href="#Set .add()">Set .add()</a></li>
<li><a href="#itertools.combinations_with_replacement()">itertools.combinations_with_replacement()</a></li>
<li><a href="#Set .discard(), .remove() & .pop()">Set .discard(), .remove() & .pop()</a></li>
<li><a href="#Collections.deque()">Collections.deque()</a></li>
<li><a href="#Set .union() Operation">Set .union() Operation</a></li>
<li><a href="#Set .intersection() Operation">Set .intersection() Operation</a></li>
<li><a href="#Mod Divmod">Mod Divmod</a></li>
<li><a href="#Power - Mod Power">Power - Mod Power</a></li>
<li><a href="#Set .difference() Operation">Set .difference() Operation</a></li>
<li><a href="#Integers Come In All Sizes">Integers Come In All Sizes</a></li>
<li><a href="#Set Mutations">Set Mutations</a></li>
<li><a href="#The Captain's Room">The Captain's Room</a></li>
<li><a href="#Check Subset">Check Subset</a></li>
<li><a href="#Check Strict Superset">Check Strict Superset</a></li>
<li><a href="#Zipped!">Zipped!</a></li>
<li><a href="#Input()">Input()</a></li>
<li><a href="#Python Evaluation">Python Evaluation</a></li>
<li><a href="#Any or All">Any or All</a></li>
<li><a href="#Detect Floating Point Number">Detect Floating Point Number</a></li>
<li><a href="#Map and Lambda Function">Map and Lambda Function</a></li>
<li><a href="#Re.split()">Re.split()</a></li>
<li><a href="#Group(), Groups() & Groupdict()">Group(), Groups() & Groupdict()</a></li>
<li><a href="#Re.findall() & Re.finditer()">Re.findall() & Re.finditer()</a></li>
<li><a href="#Validating Roman Numerals">Validating Roman Numerals</a></li>
<li><a href="#Validating phone numbers">Validating phone numbers</a></li>
<li><a href="#Validating and Parsing Email Addresses">Validating and Parsing Email Addresses</a></li>
<li><a href="#Validating UID">Validating UID</a></li>
<li><a href="#Arrays">Arrays</a></li>
<li><a href="#Shape and Reshape">Shape and Reshape</a></li>
<li><a href="#Transpose and Flatten">Transpose and Flatten</a></li>
<li><a href="#Concatenate">Concatenate</a></li>
<li><a href="#Zeros and Ones">Zeros and Ones</a></li>
<li><a href="#Eye and Identity">Eye and Identity</a></li>
<li><a href="#Array Mathematics">Array Mathematics</a></li>
<li><a href="#Floor, Ceil and Rint">Floor, Ceil and Rint</a></li>
<li><a href="#Sum and Prod">Sum and Prod</a></li>
<li><a href="#Min and Max">Min and Max</a></li>
<li><a href="#Mean, Var, and Std">Mean, Var, and Std</a></li>
<li><a href="#Dot and Cross">Dot and Cross</a></li>
<li><a href="#Inner and Outer">Inner and Outer</a></li>
<li><a href="#Linear Algebra">Linear Algebra</a></li>
<li><a href="#Re.start() & Re.end()">Re.start() & Re.end()</a></li>


  > ### DIFFICULTY: 
  > - [ ] Easy
  > - [X] Medium
  > - [ ] Hard
  
<li><a href="#Merge the Tools!">Merge the Tools!</a></li>
<li><a href="#Company Logo">Company Logo</a></li>
<li><a href="#The Minion Game">The Minion Game</a></li>
<li><a href="#Time Delta">Time Delta</a></li>
<li><a href="#Find Angle MBC">Find Angle MBC</a></li>
<li><a href="#No Idea!">No Idea!</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>
<li><a href="#Write_Here">Write_Here</a></li>

<a id='Say "Hello, World!" With Python'></a>
### Say "Hello, World!" With Python

In [ ]:
if __name__ == '__main__':
    print('Hello, World!')

### Python If-Else
<a id='Python If-Else'></a>

In [ ]:
if __name__ == '__main__':
    n = int(input().strip())    
    while(n < 1 or n > 100):
        n = int(input().strip())
    if n % 2 == 0:
        if n in list(range(2, 6)):
            print('Not Weird')
        if n in list(range(6, 21)):
            print('Weird')
        if n > 20:
            print('Not Weird')
    else:
        print('Weird')

### Arithmetic Operators
<a id='Arithmetic Operators'></a>

In [ ]:
if __name__ == '__main__':
    a = int(input())
    while(a < 1):
        a = int(input())
    b = int(input())
    while(b < 1):
        b = int(input())
    print(a + b)
    print(a - b)
    print(a * b)

### Python: Division
<a id='Python: Division'></a>

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    while(b == 0):
        print("We can't Division by zero")
        b = int(input())
    print(a//b)
    print(a/b)

### Loops
<a id='Loops'></a>

In [ ]:
if __name__ == '__main__':
    n = int(input())
    while(n < 1 or n > 20):
        n = int(input())
    for i in range(n):
        print(i**2)

<a id='Print Function'></a>
### Print Function



In [ ]:
if __name__ == '__main__':
    n = int(input())
    while(n < 1 or n > 150):
        n = int(input())
    print(''.join([str(i+1) for i in range(n)]))

### Write a function
<a id='Write a function'></a>

In [ ]:
def is_leap(year):
    leap = False
    
    if year % 4 == 0 and (year % 400 == 0 or year % 100 != 0):
                leap = True
    
    return leap

year = int(input())
print(is_leap(year))

### collections.Counter()
<a id='collections.Counter()'></a>
A counter is a container that stores elements as dictionary keys, and their counts are stored as dictionary values.

In [ ]:
from collections import Counter

X = int(input()) # the number of shoes
shoe_sizes = input()

shoe_sizes = Counter(shoe_sizes.split())

N = int(input().strip()) # the number of customers
total_price = 0

#  the shoe size desired by the customer and the price of the shoe
# compute the price of the shoes that are available 
for _ in range(N):
    size, price = map(int,input().split())
    for shoe_size, number in shoe_sizes.items():
        if size == int(shoe_size) and shoe_sizes[shoe_size] != 0:
            shoe_sizes[shoe_size] -= 1
            total_price += price
print(total_price)

### List Comprehensions
<a id='List Comprehensions'></a>


In [ ]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    coordinates = []
    for i in range(x+1):
        for j in range(y+1):
            for k in range(z+1):
                if i+j+k != n:
                    coordinates.append([i, j, k])
    print(coordinates)

### Find the Runner-Up Score!
<a id='Find the Runner-Up Score!'></a>

In [ ]:
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    arr.sort()
    runner_up = arr[0]
    maximum = arr[-1]
    for score in arr:
        if score > runner_up and score < maximum:
            runner_up = score
    print(runner_up)

### Nested Lists
<a id='Nested Lists'></a>



In [ ]:
if __name__ == '__main__':
    records = []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        records.append([name, score])
    records.sort(key = lambda s:s[1])
    lowest = records[0]
    sec_lowest = [records[-1]]
    for name, score in records:
        if score <= sec_lowest[0][1] and score > lowest[1]:
            sec_lowest.append([name, score])
            sec_lowest.sort(key = lambda s:s[1])
    del sec_lowest[-1]
    for name, score in sorted(sec_lowest):
        print(name)

### Finding the percentage
<a id='Finding the percentage'></a>

In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    print('{:.2f}'.format(sum(student_marks[query_name])/len(student_marks[query_name])))

<a id='Lists'></a>
### Lists



In [ ]:
if __name__ == '__main__':
    N = int(input())
    arr = []
    for _ in range(N):
        command, *line = input().split()
        if line and command == 'insert':
            index, value = int(line[0]), int(line[1])
        elif line and (command == 'append' or command == 'remove'):
            value = int(line[0])
        if command == 'insert':
            arr.insert(index, value)
        elif command == 'append':
            arr.append(value)
        elif command == 'remove':
            arr.remove(value)
        elif command == 'pop':
            arr.pop()
        elif command == 'sort':
            arr.sort()
        elif command == 'reverse':
            arr.reverse()
        elif command == 'print':
            print(arr)

### Tuples
<a id='Tuples'></a>


In [ ]:
if __name__ == '__main__':
    n = int(input())
    integer_list = tuple(map(int, input().strip().split()))
    print(hash(integer_list))

In [ ]:
print(input() == 0 or hash(tuple(map(int, input().split(' ')))))

### sWAP cASE
<a id='sWAP cASE'></a>

In [ ]:
def swap_case(s):
    for index, character in enumerate(s):
        if character.islower():
            character = character.upper()
        else:
            character = character.lower()
        if index == 0:
            s = character + s[1:]
        elif index == len(s) - 1:
            s = s[:-1] + character
        else:
            s = s[:index] + character + s[index+1:]
    return s

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

### String Split and Join

<a id='String Split and Join'></a>


In [ ]:
def split_and_join(line):
    return '-'.join(line.split())

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

### What's Your Name?
<a id="What's Your Name?"></a>

In [ ]:
#
# Complete the 'print_full_name' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING last
#

def print_full_name(first, last):
    print(f'Hello {first} {last}! You just delved into python.')

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

### Mutations
<a id='Mutations'></a>

In [ ]:
def mutate_string(string, position, character):
    l = list(string)
    l[position] = character
    string = ''.join(l)
    return string

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

### Find a string
<a id='Find a string'></a>

In [ ]:
def count_substring(string, sub_string):
    count = 0
    while string.find(sub_string) != -1:
        index = string.find(sub_string)
        count +=1
        string = string[index + 1:]    
    return count

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

### String Validators
<a id='String Validators'></a>

In [ ]:
if __name__ == '__main__':
    s = input()
    conditions = [False, False, False, False, False]
    for ch in s:
        if ch.isalnum():
            conditions[0] = True
        if ch.isalpha():
            conditions[1] = True
        if ch.isdigit():
            conditions[2] = True
        if ch.islower():
            conditions[3] = True
        if ch.isupper():
            conditions[4] = True
    for condition in conditions:
        print(condition)

### Text Alignment
<a id='Text Alignment'></a>

In [ ]:
#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))


### Text Wrap
<a id='Text Wrap'></a>

In [ ]:
import textwrap

def wrap(string, max_width):
    wrap_string = ''
    while(len(string) > max_width):
        wrap_string = wrap_string + string[:max_width]+'\n'
        string = string[max_width:]
    return wrap_string + string

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

### Designer Door Mat
<a id='Designer Door Mat'></a>

In [ ]:
length, width = map(int, input().strip().split())
odd_numbers = [odd for odd in range(1, length, 2)]
for num in odd_numbers:
    print('-' * ((width - (3 * num)) // 2) + '.|.' * num + '-' * ((width - (3 * num)) // 2))
    
print('-' * ((width - 7) // 2) + 'WELCOME' + '-' * ((width - 7) // 2))
        
for num in reversed(odd_numbers):
    print('-' * ((width - (3 * num)) // 2) + '.|.' * num + '-' * ((width - (3 * num)) // 2))

### String Formatting
<a id='String Formatting'></a>


In [ ]:
def print_formatted(number):
    space_padded = len(bin(number)[2:])
    for num in range(1, number + 1):
        print(str(num).rjust(space_padded), oct(num)[2:].rjust(space_padded),
              hex(num)[2:].upper().rjust(space_padded), bin(num)[2:].rjust(space_padded))
        

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

### Alphabet Rangoli
<a id='Alphabet Rangoli'></a>

In [ ]:
def print_rangoli(size):
    alphabet_string = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
     'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    rows = (size * 2 - 1)
    columns = (size * 2 - 1) + (size -1) * 2
    # a list of characters count in each row
    characters_count = list(range(1, rows + 1, 2))
    # list of  the specific characters
    alphabet_string = alphabet_string[:size]
    alphabet_string.reverse()
    alphabet = ''
    rangoli = ''
    for ch_num in characters_count:
        line = []
        for ch_index in range(ch_num):
            if ch_index < ch_num // 2:
                line.append(alphabet_string[ch_index])
            else:
                line.append(alphabet_string[ch_num-ch_index-1])
        alphabet = '-'.join(line)
        rangoli = rangoli + '-'*((columns - len(alphabet))//2) + alphabet + '-'*((columns - len(alphabet))//2) +'\n'
        
    for ch_num in reversed(characters_count[:-1]):
        line = []
        for ch_index in range(ch_num):
            if ch_index < ch_num // 2:
                line.append(alphabet_string[ch_index])
            else:
                line.append(alphabet_string[ch_num-ch_index-1])
        alphabet = '-'.join(line)
        rangoli = rangoli + '-'*((columns - len(alphabet))//2) + alphabet + '-'*((columns - len(alphabet))//2) +'\n' 
    
    print(rangoli)
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

### Capitalize!

<a id='Capitalize!'></a>


In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    return ' '.join(word.capitalize() for word in s.split(' '))
    #return ' '.join(map(str.capitalize, s.split(' ')))


if __name__ == '__main__':
    fptr = open('passport_name.txt', 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()


### itertools.product()
<a id='itertools.product()'></a>


In [ ]:
from itertools import product
A = sorted(list(set(map(int, input().strip().split()))))
B = sorted(list(set(map(int, input().strip().split()))))
cartesian_product = sorted(list(product(A, B)))
print(' '.join([str(value) for value in cartesian_product]))

### itertools.permutations()
<a id='itertools.permutations()'></a>


In [ ]:
from itertools import permutations
s, k = input().strip().split(' ')
permutations = sorted(list(permutations(s.upper(), int(k))))
for permutation in permutations:
    print(''.join(permutation))

### Polar Coordinates
<a id='Polar Coordinates'></a>


In [ ]:
from cmath import phase
z = complex(input().strip())
print(abs(z))
print(phase(z))

### Introduction to Sets
<a id='Introduction to Sets'></a>


In [ ]:
def average(array):
    return round(sum(set(array))/len(set(array)), 3)

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

<a id='DefaultDict Tutorial'></a>
### DefaultDict Tutorial

In [ ]:
from collections import defaultdict
n, m = map(int, input().strip().split())
a_b_groups = defaultdict(list)
for _ in range(n):
    a_b_groups['A'].append(input().strip())
for _ in range(m):
    a_b_groups['B'].append(input().strip())
    
for word_b in a_b_groups['B']:
    index = 0
    if word_b in a_b_groups['A']:
        for word_a in a_b_groups['A']:
            if word_b == word_a:
                index = a_b_groups['A'].index(word_b)
                a_b_groups['A'][index] = a_b_groups['A'][index].upper()
                print( index + 1, end = ' ')
        print()
    else:
        print(-1)

<a id='Calendar Module'></a>
### Calendar Module

In [ ]:
import datetime
import calendar
month, day, year = input().strip().split()
print(calendar.day_name[datetime.date(day=int(day), month=int(month), year=int(year)).weekday()].upper())

### Exceptions
<a id='Refer_to'></a>


In [ ]:
try:
    print (1/0)
except ZeroDivisionError as e:
    print ("Error Code:",e)

In [ ]:
num_cases = int(input().strip())
test_cases = []
for _ in range(num_cases):
    test_cases.append(list(map(str, input().split())))
    
for case in test_cases:
    try: 
        print(int(case[0])//int(case[1]))
    except ZeroDivisionError:
        print('Error Code:', 'integer division or modulo by zero')
    except ValueError as e:
        print('Error Code:', e)

 <a id='Collections.namedtuple()'></a>
### Collections.namedtuple()

In [ ]:
from collections import namedtuple
total_students, headers, total = int(input().strip()), input().strip().split(), 0
student = namedtuple('student',headers)
for _ in range(total_students):
    student_data = student._make(input().strip().split())
    total += int(student_data.MARKS)
print(round(total/total_students, ndigits = 2))

In [ ]:
N, headers, total = int(input()), list(input().split()), 0
for _ in range(N):
    total += int(list(input().split())[headers.index('MARKS')])
print(total/N)

<a id='Collections.OrderedDict()'></a>
### Collections.OrderedDict()

In [ ]:
from collections import OrderedDict
num_items = int(input().strip())

items_data = OrderedDict()
for _ in range(num_items):
    item_data = input().strip().split()
    item = ' '.join(item_data[:-1])
    price = int(item_data[-1])
    if item in items_data:
        items_data[item] += price
    else:
        items_data[item] = price
for item, net_price in items_data.items():
    print(item, net_price)

## 🏆 Gold Badge 🏆 

<a id='Symmetric Difference'></a>
### Symmetric Difference

In [ ]:
M = input().strip()
set1 = set(map(int, input().strip().split()))
N = input().strip()
set2 = set(map(int, input().strip().split()))
symmetric_difference = set1.difference(set2)
symmetric_difference.update(set2.difference(set1))

for num in sorted(symmetric_difference):
    print(num)

<a id='itertools.combinations()'></a>
### itertools.combinations()

In [ ]:
from itertools import combinations

string, up_to = input().strip().split()

for num in range(1, int(up_to)+1):
    for chs in sorted(combinations(sorted(string.upper()), num)):
        print(''.join(list(chs)))

<a id='Incorrect Regex'></a>
### Incorrect Regex

In [ ]:
import re
num_cases = int(input().strip())
is_regex = []
for _ in range(num_cases):
    case = input().strip()
    try:
        if re.compile(case):
            is_regex.append(True)
    except:
        is_regex.append(False)
for status in is_regex:
    print(status)

<a id='Set .add()'></a>
### Set .add()

In [ ]:
num_stamps = int(input().strip())
country_stamps = set()
for _ in range(num_stamps):
    country_stamps.add(input())
print(len(country_stamps))

<a id='itertools.combinations_with_replacement()'></a>
### itertools.combinations_with_replacement()

In [ ]:
from itertools import combinations_with_replacement
string, num = input().strip().split()
for values in combinations_with_replacement(sorted(string.upper()), int(num)):
        print(''.join(list(values)))

### Set .discard(), .remove() & .pop()
<a id='Set .discard(), .remove() & .pop()'></a>


In [ ]:
elements_num = int(input().strip())
elements = set(map(int, input().strip().split()))
commands_num = int(input().strip())
for _ in range(commands_num):
    command = input().strip().split(' ')
    if len(command) == 2:
        if command[0] == 'remove':
            elements.remove(int(command[1]))
        elif command [0] == 'discard':
            elements.discard(int(command[1]))
    elif len(command) == 1:
        if command[0] == 'pop':
            elements.pop()
print(sum(elements))

### Collections.deque()
<a id='Collections.deque()'></a>

In [ ]:
from collections import deque
ops_num = int(input().strip())
d = deque()
for _ in range(ops_num):
    command = input().strip().split()
    if command[0] == 'append':
        d.append(int(command[1]))
    elif command[0] == 'pop':
        d.pop()
    elif command[0] == 'popleft':
        d.popleft()
    elif command[0] == 'appendleft':
        d.appendleft(int(command[1]))
for value in d:
    print(value, end = ' ')

### Set .union() Operation
<a id='Set .union() Operation'></a>

In [ ]:
en_studs_num = int(input().strip())
students_en = set(map(int, input().strip().split()))
fr_studs_num = int(input().strip())
students_fr = set(map(int, input().strip().split()))
print(len(students_en | students_fr)) 
# print(len(students_en.union(students_fr)))

<a id='Set .intersection() Operation'></a>
### Set .intersection() Operation

In [ ]:
en_studs_num = int(input().strip())
students_en = set(map(int, input().strip().split()))
fr_studs_num = int(input().strip())
students_fr = set(map(int, input().strip().split()))
print(len(students_en & students_fr)) 
# print(len(students_en.intersection(students_fr)))

<a id='Mod Divmod'></a>
### Mod Divmod

In [ ]:
a = int(input().strip())
b = int(input().strip())
int_div_modulo = divmod(a, b)
for value in int_div_modulo:
    print(value)
print(int_div_modulo)

<a id='Power - Mod Power'></a>
### Power - Mod Power

In [ ]:
a = int(input().strip())
b = int(input().strip())
m = int(input().strip())
print(pow(a, b))
if b > 0:
    print(pow(a, b, m))

<a id='Set .difference() Operation'></a>
### Set .difference() Operation

In [ ]:
en_studs_num = int(input().strip())
students_en = set(map(int, input().strip().split()))
fr_studs_num = int(input().strip())
students_fr = set(map(int, input().strip().split()))
print(len(students_en.difference(students_fr))) 
# print(len(students_en - students_fr))

<a id='Integers Come In All Sizes'></a>
### Integers Come In All Sizes

In [ ]:
a = int(input().strip())
b = int(input().strip())
c = int(input().strip())
d = int(input().strip())
print(pow(a, b) + pow(c, d))

<a id='Set .symmetric_difference() Operation'></a>
### Set .symmetric_difference() Operation

In [ ]:
en_studs_num = int(input().strip())
students_en = set(map(int, input().strip().split()))
fr_studs_num = int(input().strip())
students_fr = set(map(int, input().strip().split()))
print(len(students_en.symmetric_difference(students_fr))) 
# print(len(students_en ^ students_fr))

<a id='Set Mutations'></a>
### Set Mutations

In [ ]:
num_elements = int(input().strip())
elements = set(map(int, input().strip().split()))

num_sets = int(input().strip())

for _ in range(num_sets):
    command = input().split()
    eles = set(map(int, input().strip().split()))
    if command[0] == 'update':
        elements.update(eles)
    elif command[0] == 'difference_update':
        elements.difference_update(eles)
    elif command[0] == 'symmetric_difference_update':
        elements.symmetric_difference_update(eles)
    elif command[0] == 'intersection_update':
        elements.intersection_update(eles)
               
print(sum(elements))

<a id="The Captain's Room"></a>
### The Captain's Room

In [ ]:
groups_size, room_numbers, single, multiple = input(), input().split(), set(), set()
for room in room_numbers:
    if room not in single:
        single.add(room)
    else:
        multiple.add(room)
print(single.difference(multiple).pop())

<a id='Check Subset'></a>
### Check Subset

In [ ]:
n_test_cases = int(input())
is_subset = []
for _ in range(n_test_cases):
    n_eles_A = input()
    A = set(map(int, input().split(' ')))
    n_eles_B = input()
    B = set(map(int, input().split(' ')))
    if A.issubset(B):
        is_subset.append(True)
    else:
        is_subset.append(False)
for condition in is_subset:
    print(condition)

<a id='Check Strict Superset'></a>
### Check Strict Superset

In [ ]:
A = set(map(int, input().strip().split(' ')))
n_sets = int(input().strip())
is_strict_superset = False
for _ in range(n_sets):
    test_set = set(map(int, input().split(' ')))
    if A.issuperset(test_set) and len(A) > len(test_set):
        is_strict_superset = True
    else:
        is_strict_superset = False
        break
print(is_strict_superset)

<a id='Zipped!'></a>
### Zipped!

In [ ]:
n_students, n_subjects = input().strip().split(' ')
students_scores = []
for _ in range(int(n_subjects)):
    students_scores.append(tuple(map(float, input().strip().split())))
for student_scores in zip(*students_scores):
    print(round(sum(student_scores)/len(student_scores), ndigits=1))

<a id='Input()'></a>
### Input()

In [ ]:
x, k = input().strip().split()
x, k = int(x), float(k)
if eval(input()) == k:
    print(True)
else:
    print(False)

<a id='Python Evaluation'></a>
### Python Evaluation

In [ ]:
var = input().strip()
if eval(var) != None: #  Here the result of print(2 + 5) is displayed
    print(eval(var))  # In the case of a function returns 'None' as 'print' function, this line is not executed.

<a id='Any or All'></a>
### Any or All

In [ ]:
list_size, list_of_integers = int(input().strip()), input().strip().split()
print(all([int(val) > 0 for val in list_of_integers]) & any(s == s[::-1] for s in list_of_integers))

<a id='Detect Floating Point Number'></a>
### Detect Floating Point Number

In [ ]:
is_float = []
n_tests = int(input().strip())
for _ in range(n_tests):
    try:
        num = input().strip()
        int(num.split('.')[1]) # Check for that the number must contain at least 1 decimal value.
        if float(num):
            is_float.append(True)
        else:
            is_float.append(False)
    except:
        is_float.append(False)
for condition in is_float:
    print(condition)

<a id='Map and Lambda Function'></a>
### Map and Lambda Function

In [ ]:
num = int(input())

for n in range(2, num):
    val1, val2 = n-1, n-2
    fibonacci_numbers.append(fibonacci_numbers[val1] + fibonacci_numbers[val2])
print(list(map(lambda x:x**3, fibonacci_numbers)))

In [ ]:
cube = lambda x: pow(x, 3)
def fibonacci(n):
    fibonacci_numbers = [0, 1]
    for idx in range(2, n):
        fibonacci_numbers.append(fibonacci_numbers[idx-1] + fibonacci_numbers[idx-2])
    return fibonacci_numbers[0:n]

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

<a id='Re.split()'></a>
### Re.split()

[Python RegEx](https://www.w3schools.com/python/python_regex.asp)

In [112]:
regex_pattern = r"\D+"    # Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

100,100.000
100
100
000


<a id='Group(), Groups() & Groupdict()'></a>
### Group(), Groups() & Groupdict()

In [1]:
# Solution from Discussions
import re
S=input()
m=re.search(r'((\w(?!_))\2{1,})',S)
print(S[m.start()] if m else '-1')

..12345678910111213141516171820212223
1


<a id='Re.findall() & Re.finditer()'></a>
### Re.findall() & Re.finditer()

In [2]:
# Solution from Discussions
import re
v = "aeiou"
c = "qwrtypsdfghjklzxcvbnm"
m = re.findall(r"(?<=[%s])([%s]{2,})[%s]" % (c, v, c), input(), flags = re.I)
print('\n'.join(m or ['-1']))

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


<a id='Validating Roman Numerals'></a>
### Validating Roman Numerals

In [3]:
# Solution from Discussions
regex_pattern =r'^M{,3}(C(D|M)|D?C{,3})(X(L|C)|L?X{,3})(I(X|V)|(X|V)?I{,3})$' 
import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


<a id='Validating phone numbers'></a>
### Validating phone numbers

In [7]:
# Solution from Discussions
import re
N=int(input())
for i in range(N):
    if re.match(r'[789]\d{9}$',input()):   
        print('YES')  
    else:  
        print('NO')  

2
9587456281
YES
1252478965
NO


<a id='Validating and Parsing Email Addresses'></a>
### Validating and Parsing Email Addresses

In [9]:
import email.utils
import re

def main():
    pattern = re.compile(r"^[a-zA-Z][\w\-.]*@[a-zA-Z]+\.[a-zA-Z]{1,3}$")
    for _ in range(int(input())):
        u_name, u_email = email.utils.parseaddr(input())
        if pattern.match(u_email):
              print(email.utils.formataddr((u_name, u_email)))

if __name__ == "__main__":
    main()

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>


<a id='Validating UID'></a>
### Validating UID

In [19]:
n_test = int(input().strip())
for _ in range(n_test):
    ID = input().strip()
    count_uppercase = 0
    count_digits = 0
    no_repeat = False
    if len(ID) == 10 and ID.isalnum():
        for ch in ID:
            if ID.count(ch) == 1:
                no_repeat = True
                if ch.isupper():
                    count_uppercase +=1
                elif ch.isdigit():
                    count_digits += 1
            else:
                no_repeat = False
                break
                
        if count_uppercase >= 2 and count_digits >= 3 and no_repeat:
            print('Valid')
        else:
            print('Invalid')
    else:
        print('Invalid')

2
B1CD102354
Invalid
B1CDEF2354
Valid


<a id='Arrays'></a>
### Arrays

In [8]:
import numpy

def arrays(arr):
    return numpy.array(arr, float)[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


<a id='Shape and Reshape'></a>
### Shape and Reshape

In [13]:
import numpy
arr = input().strip().split(' ')
arr = numpy.array(arr, int).reshape((3, 3))

print(arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<a id='Transpose and Flatten'></a>
### Transpose and Flatten

In [22]:
import numpy
rows, cols = map(int, input().strip().split())
lst = []
for _ in range(rows):
    lst += map(int, input().strip().split())
arr = numpy.array(lst).reshape((rows, cols))
print(arr.transpose())
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


<a id='Concatenate'></a>
### Concatenate

In [23]:
import numpy
rows1, rows2, cols = map(int, input().strip().split())
arr1 = []
for _ in range(rows1):
    arr1 += map(int, input().strip().split())
arr1 = numpy.array(arr1).reshape(rows1, cols)

arr2 = []
for _ in range(rows2):
    arr2 += map(int, input().strip().split())
arr2 = numpy.array(arr2).reshape(rows2, cols)

print(numpy.concatenate((arr1, arr2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


<a id='Zeros and Ones'></a>
### Zeros and Ones

In [30]:
import numpy
shape = tuple(map(int, input().strip().split()))
print(numpy.zeros(shape, int), numpy.ones(shape, int), sep='\n')

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


<a id='Eye and Identity'></a>
### Eye and Identity

In [38]:
import numpy
numpy.set_printoptions(legacy='1.13')
shape = tuple(map(int, input().strip().split()))
eye_arr = numpy.eye(*shape)
print(eye_arr)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


<a id='Array Mathematics'></a>
### Array Mathematics

In [7]:
import numpy as np
rows, cols = map(int, input().strip().split())
arr1 = []
for _ in range(rows):
    arr1 += input().strip().split()
arr1 = np.array(arr1, int).reshape((rows, cols))

arr2 = []
for _ in range(rows):
    arr2 += input().strip().split()
arr2 = np.array(arr2, int).reshape((rows, cols))

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 // arr2)
print(arr1 % arr2)
print(arr1**arr2)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


<a id='Floor, Ceil and Rint'></a>
### Floor, Ceil and Rint

In [11]:
import numpy as np
np.set_printoptions(legacy='1.13')
arr = np.array(list(map(float, input().strip().split())))
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


<a id='Sum and Prod'></a>
### Sum and Prod

In [14]:
import numpy as np
rows, cols = map(int, input().strip().split())
arr1 = []
for _ in range(rows):
    arr1 += input().strip().split()
arr1 = np.array(arr1, int).reshape((rows, cols))
print(np.prod(np.sum(arr1, axis=0)))

2 2
1 2
3 4
24


<a id='Min and Max'></a>
### Min and Max

In [15]:
import numpy as np
rows, cols = map(int, input().strip().split())
arr1 = []
for _ in range(rows):
    arr1 += input().strip().split()
arr1 = np.array(arr1, int).reshape((rows, cols))
print(np.max(np.min(arr1, axis=1)))

4 2
2 5
3 7
1 3
4 0
3


<a id='Mean, Var, and Std'></a>
### Mean, Var, and Std

In [21]:
import numpy as np
rows, cols = map(int, input().strip().split())
arr = []
arr = np.array([input().strip().split() for _ in range(rows)], int)
mean = np.mean(arr, axis = 1)
var = np.var(arr, axis = 0)
std = np.std(arr)
print(mean)
print(var)
print(np.around(std, decimals=11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


<a id='Dot and Cross'></a>
### Dot and Cross

In [36]:
import numpy as np
N = int(input().strip())
arr1 = np.array([input().strip().split() for _ in range(N)], int)
arr2 = np.array([input().strip().split() for _ in range(N)], int)
lst = []
for id_row in range(N):
    lst.append([])
    for id_col in range(N):
        lst[id_row].append(sum(arr1[id_row] * arr2[:, id_col]))
        
matrix_multiplication = np.array(lst)
print(matrix_multiplication)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


<a id='Inner and Outer'></a>
### Inner and Outer

In [38]:
import numpy as np
arr1 = np.array(input().strip().split(), int)
arr2 = np.array(input().strip().split(), int)
print(np.inner(arr1, arr2))
print(np.outer(arr1, arr2))

0 1
 2 3
3
[[0 0]
 [2 3]]


<a id='Linear Algebra'></a>
### Linear Algebra

In [41]:
import numpy as np
N = int(input().strip())
arr = np.array([input().strip().split() for _ in range(N)], float)
print(np.around(np.linalg.det(arr), decimals=2))

2
1.1 1.1
1.1 1.1
0.0


<a id='Re.start() & Re.end()'></a>
### Re.start() & Re.end()

In [43]:
# Solution from discussions
# Enter your code here. Read input from STDIN. Print output to STDOUT
S = input()
k = input()
import re
pattern = re.compile(k)
r = pattern.search(S)
if not r: print("(-1, -1)")
while r:
    print("({0}, {1})".format(r.start(), r.end() - 1))
    r = pattern.search(S,r.start() + 1)

aaadaa
aa
(0, 1)
(1, 2)
(4, 5)


<a id='Decorators 2 - Name Directory'></a>
### Decorators 2 - Name Directory

In [44]:
# Solution from discussions
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        return (f(spers) for spers in sorted((person[:2]+[int(person[2])]+person[3:]+[idx] for idx, person in enumerate(people)), key=operator.itemgetter(2, 4)))          
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


<a id='Merge the Tools!'></a>
### Merge the Tools!

In [32]:
def merge_the_tools(string, k):
    # your code goes here
    n = len(string)
    for _ in range(n//k):
        substring = string[:k]
        string = string[k:]
        for ch in substring:
            if substring.count(ch) > 1:
                index = substring.rfind(ch)
                if index == len(substring) - 1:
                    substring = substring[:-1]
                else:
                    substring = substring[:index] + substring[index+1:]
        print(substring)
if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

AABCAAADA
3
AB
CA
AD


<a id='Company Logo'></a>
### Company Logo

In [42]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    s = input()
    characters = {}
    
    for ch in set(s):
        characters[ch] = s.count(ch)
        
    for key, value in sorted(characters.items(), key=lambda x :(-x[1], x[0]))[:3]:
        print(key, value)

aabbbccde
b 3
a 2
c 2


<a id='The Minion Game'></a>
### The Minion Game

In [47]:
def minion_game(string):
    vowels = 'AEIOU'
    kevsc = 0
    stusc = 0
    for i in range(len(s)):
        if s[i] in vowels:
            kevsc += (len(s)-i)
        else:
            stusc += (len(s)-i)

    if kevsc > stusc:
        print( "Kevin", kevsc)
    elif kevsc < stusc:
        print( "Stuart", stusc)
    else:
        print("Draw")


if __name__ == '__main__':
    s = input()
    minion_game(s)

BANANA
Stuart 12


<a id='Time Delta'></a>
### Time Delta

In [4]:
#!/bin/python3

import math
import os
import random
import re
import sys
from datetime import datetime as dt
# Complete the time_delta function below.
def time_delta(t1, t2):
    fmt = '%a %d %b %Y %H:%M:%S %z'
    diff = int(abs((dt.strptime(t1, fmt) - 
                       dt.strptime(t2, fmt)).total_seconds()))
    print(diff)
    return diff
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(str(delta) + '\n')

    fptr.close()

2
Sun 10 May 2015 13:54:36 -0700
Sun 10 May 2015 13:54:36 -0000
25200
Sat 02 May 2015 19:54:36 +0530
Fri 01 May 2015 13:54:36 -0000
88200


<a id='Find Angle MBC'></a>
### Find Angle MBC

In [14]:
import math
ab = int(input().strip()) 
bc = int(input().strip())
angle = str(int(round(math.degrees(math.atan(ab/bc))))) + u"\N{DEGREE SIGN}"
print(angle)

10
10
45°


<a id='No Idea!'></a>
### No Idea!

In [17]:
n, m = map(int, input().strip().split())
arr = map(int, input().strip().split())
A = set(map(int, input().strip().split()))
B = set(map(int, input().strip().split()))
happiness = 0
for val in arr:
    if val in A:
        happiness += 1
    if val in B:
        happiness -= 1
        
print(happiness)

3 2
1 5 3
3 1
5 7
1


In [ ]:
<a id='Refer_to'></a>
### Refer_to

In [ ]:
<a id='Refer_to'></a>
### Refer_to

In [ ]:
<a id='Refer_to'></a>
### Refer_to

In [ ]:
<a id='Refer_to'></a>
### Refer_to

In [ ]:
<a id='Refer_to'></a>
### Refer_to

In [ ]:
<a id='Refer_to'></a>
### Refer_to

In [ ]:
<a id='Refer_to'></a>
### Refer_to